# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html

# Baseado no link https://gist.github.com/tjamps/11d617a4b318d65ca583
security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    providers:
        fos_userbundle:
            # fos_user.user_provider.username_email does not seem to work (OAuth-spec related ("username + password") ?)
            id: fos_user.user_provider.username
    firewalls:
        oauth_token:
            # localização do recurso token
            pattern: ^/oauth/v2/token
            security: false
        api:
            pattern: ^/api
            # vou proteger os recursos com oauth2
            fos_oauth: true
            # não guardarei cookie de sessão
            stateless: true
            # acesso anonimo está autorizado
            anonymous: true