# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    enquete_business:
        class: AppBundle\Business\EnqueteBusiness
        arguments: ["@service_container", "AppBundle:Enquete"]
    avaliacao_business:
        class: AppBundle\Business\AvaliacaoBusiness
        arguments: ["@service_container", "AppBundle:Enquete"]